package com.Wsdl2Code.WebServices.MiWebService1;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 4/27/2015 3:18:20 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class datos_persona_entrada implements KvmSerializable {
    
    public String nombre;
    public String email;
    public String telefono;
    public int ano_nac;
    
    public datos_persona_entrada(){}
    
    public datos_persona_entrada(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("nombre"))
        {
            Object obj = soapObject.getProperty("nombre");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                nombre = j.toString();
            }else if (obj!= null && obj instanceof String){
                nombre = (String) obj;
            }
        }
        if (soapObject.hasProperty("email"))
        {
            Object obj = soapObject.getProperty("email");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                email = j.toString();
            }else if (obj!= null && obj instanceof String){
                email = (String) obj;
            }
        }
        if (soapObject.hasProperty("telefono"))
        {
            Object obj = soapObject.getProperty("telefono");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                telefono = j.toString();
            }else if (obj!= null && obj instanceof String){
                telefono = (String) obj;
            }
        }
        if (soapObject.hasProperty("ano_nac"))
        {
            Object obj = soapObject.getProperty("ano_nac");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                ano_nac = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                ano_nac = (Integer) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return nombre;
            case 1:
                return email;
            case 2:
                return telefono;
            case 3:
                return ano_nac;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "nombre";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "email";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "telefono";
                break;
            case 3:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ano_nac";
                break;
        }
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
