package com.Wsdl2Code.WebServices.MiWebService1;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 4/27/2015 3:18:20 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.MiWebService1.WS_Enums.*;
import java.util.List;
import org.ksoap2.SoapEnvelope;
import org.ksoap2.SoapFault;
import org.ksoap2.serialization.SoapSerializationEnvelope;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.HeaderProperty;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import android.os.AsyncTask;
import org.ksoap2.serialization.MarshalFloat;

public class MiWebService1 {
    
    public String NAMESPACE ="urn:mi_ws1";
    public String url="http://xhendor.me/ws/hello.php";
    public int timeOut = 60000;
    public IWsdl2CodeEvents eventHandler;
    public SoapProtocolVersion soapVersion;
    
    public MiWebService1(){}
    
    public MiWebService1(IWsdl2CodeEvents eventHandler)
    {
        this.eventHandler = eventHandler;
    }
    public MiWebService1(IWsdl2CodeEvents eventHandler,String url)
    {
        this.eventHandler = eventHandler;
        this.url = url;
    }
    public MiWebService1(IWsdl2CodeEvents eventHandler,String url,int timeOutInSeconds)
    {
        this.eventHandler = eventHandler;
        this.url = url;
        this.setTimeOut(timeOutInSeconds);
    }
    public void setTimeOut(int seconds){
        this.timeOut = seconds * 1000;
    }
    public void setUrl(String url){
        this.url = url;
    }
    public void calculo_edadAsync(datos_persona_entrada datos_persona_entrada) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        calculo_edadAsync(datos_persona_entrada, null);
    }
    
    public void calculo_edadAsync(final datos_persona_entrada datos_persona_entrada,final List<HeaderProperty> headers) throws Exception{
        
        new AsyncTask<Void, Void, datos_persona_salidad>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected datos_persona_salidad doInBackground(Void... params) {
                return calculo_edad(datos_persona_entrada, headers);
            }
            @Override
            protected void onPostExecute(datos_persona_salidad result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("calculo_edad", result);
                }
            }
        }.execute();
    }
    
    public datos_persona_salidad calculo_edad(datos_persona_entrada datos_persona_entrada){
        return calculo_edad(datos_persona_entrada, null);
    }
    
    public datos_persona_salidad calculo_edad(datos_persona_entrada datos_persona_entrada,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("urn:mi_ws1","calculo_edad");
        soapEnvelope.addMapping("urn:mi_ws1","datos_persona_entrada",new datos_persona_entrada().getClass());
        soapReq.addProperty("datos_persona_entrada",datos_persona_entrada);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("urn:mi_ws1/calculo_edad", soapEnvelope,headers);
            }else{
                httpTransport.call("urn:mi_ws1/calculo_edad", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    datos_persona_salidad resultVariable =  new datos_persona_salidad (j);
                    return resultVariable;
                    
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }
    
}
